# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'Main_Test.ui'
##
## Created by: Qt User Interface Compiler version 6.7.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QCheckBox, QComboBox, QFormLayout,
    QFrame, QHeaderView, QLabel, QLayout,
    QLineEdit, QPushButton, QScrollArea, QSizePolicy,
    QTableView, QTextEdit, QWidget)

class Ui_frmMainTest(object):
    def setupUi(self, frmMainTest):
        if not frmMainTest.objectName():
            frmMainTest.setObjectName(u"frmMainTest")
        frmMainTest.resize(1100, 726)
        font = QFont()
        font.setPointSize(11)
        frmMainTest.setFont(font)
        self.scrollArea = QScrollArea(frmMainTest)
        self.scrollArea.setObjectName(u"scrollArea")
        self.scrollArea.setGeometry(QRect(12, 228, 343, 487))
        self.scrollArea.setFocusPolicy(Qt.ClickFocus)
        self.scrollArea.setWidgetResizable(True)
        self.scrollAreaWidgetContents = QWidget()
        self.scrollAreaWidgetContents.setObjectName(u"scrollAreaWidgetContents")
        self.scrollAreaWidgetContents.setGeometry(QRect(0, 0, 341, 485))
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.btnStart = QPushButton(frmMainTest)
        self.btnStart.setObjectName(u"btnStart")
        self.btnStart.setGeometry(QRect(972, 36, 115, 40))
        font1 = QFont()
        font1.setPointSize(11)
        font1.setBold(True)
        self.btnStart.setFont(font1)
        self.btnStop = QPushButton(frmMainTest)
        self.btnStop.setObjectName(u"btnStop")
        self.btnStop.setGeometry(QRect(972, 78, 115, 40))
        self.btnStop.setFont(font1)
        self.btnExit = QPushButton(frmMainTest)
        self.btnExit.setObjectName(u"btnExit")
        self.btnExit.setGeometry(QRect(972, 162, 115, 40))
        self.btnExit.setFont(font1)
        self.formLayoutWidget_2 = QWidget(frmMainTest)
        self.formLayoutWidget_2.setObjectName(u"formLayoutWidget_2")
        self.formLayoutWidget_2.setGeometry(QRect(288, 36, 283, 139))
        self.formLayout_2 = QFormLayout(self.formLayoutWidget_2)
        self.formLayout_2.setObjectName(u"formLayout_2")
        self.formLayout_2.setSizeConstraint(QLayout.SetDefaultConstraint)
        self.formLayout_2.setFieldGrowthPolicy(QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_2.setRowWrapPolicy(QFormLayout.DontWrapRows)
        self.formLayout_2.setHorizontalSpacing(6)
        self.formLayout_2.setContentsMargins(0, 0, 0, 0)
        self.label_5 = QLabel(self.formLayoutWidget_2)
        self.label_5.setObjectName(u"label_5")

        self.formLayout_2.setWidget(0, QFormLayout.LabelRole, self.label_5)

        self.cboScript = QComboBox(self.formLayoutWidget_2)
        self.cboScript.setObjectName(u"cboScript")
        self.cboScript.setFocusPolicy(Qt.ClickFocus)

        self.formLayout_2.setWidget(0, QFormLayout.FieldRole, self.cboScript)

        self.Label = QLabel(self.formLayoutWidget_2)
        self.Label.setObjectName(u"Label")

        self.formLayout_2.setWidget(2, QFormLayout.LabelRole, self.Label)

        self.cboReportNo = QComboBox(self.formLayoutWidget_2)
        self.cboReportNo.setObjectName(u"cboReportNo")
        sizePolicy = QSizePolicy(QSizePolicy.Policy.Preferred, QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cboReportNo.sizePolicy().hasHeightForWidth())
        self.cboReportNo.setSizePolicy(sizePolicy)
        self.cboReportNo.setMinimumSize(QSize(0, 0))
        self.cboReportNo.setFocusPolicy(Qt.ClickFocus)

        self.formLayout_2.setWidget(2, QFormLayout.FieldRole, self.cboReportNo)

        self.label_6 = QLabel(self.formLayoutWidget_2)
        self.label_6.setObjectName(u"label_6")

        self.formLayout_2.setWidget(3, QFormLayout.LabelRole, self.label_6)

        self.ltxtStartTime = QLineEdit(self.formLayoutWidget_2)
        self.ltxtStartTime.setObjectName(u"ltxtStartTime")
        self.ltxtStartTime.setFocusPolicy(Qt.ClickFocus)

        self.formLayout_2.setWidget(3, QFormLayout.FieldRole, self.ltxtStartTime)

        self.ltxtSpendTime = QLineEdit(self.formLayoutWidget_2)
        self.ltxtSpendTime.setObjectName(u"ltxtSpendTime")
        self.ltxtSpendTime.setFocusPolicy(Qt.ClickFocus)

        self.formLayout_2.setWidget(4, QFormLayout.FieldRole, self.ltxtSpendTime)

        self.label_7 = QLabel(self.formLayoutWidget_2)
        self.label_7.setObjectName(u"label_7")

        self.formLayout_2.setWidget(4, QFormLayout.LabelRole, self.label_7)

        self.label_10 = QLabel(self.formLayoutWidget_2)
        self.label_10.setObjectName(u"label_10")

        self.formLayout_2.setWidget(1, QFormLayout.LabelRole, self.label_10)

        self.ltxtScriptVer = QLineEdit(self.formLayoutWidget_2)
        self.ltxtScriptVer.setObjectName(u"ltxtScriptVer")
        self.ltxtScriptVer.setFocusPolicy(Qt.ClickFocus)

        self.formLayout_2.setWidget(1, QFormLayout.FieldRole, self.ltxtScriptVer)

        self.formLayoutWidget_3 = QWidget(frmMainTest)
        self.formLayoutWidget_3.setObjectName(u"formLayoutWidget_3")
        self.formLayoutWidget_3.setGeometry(QRect(12, 36, 271, 139))
        self.formLayout_3 = QFormLayout(self.formLayoutWidget_3)
        self.formLayout_3.setObjectName(u"formLayout_3")
        self.formLayout_3.setContentsMargins(0, 0, 0, 0)
        self.label_3 = QLabel(self.formLayoutWidget_3)
        self.label_3.setObjectName(u"label_3")

        self.formLayout_3.setWidget(0, QFormLayout.LabelRole, self.label_3)

        self.label_4 = QLabel(self.formLayoutWidget_3)
        self.label_4.setObjectName(u"label_4")

        self.formLayout_3.setWidget(1, QFormLayout.LabelRole, self.label_4)

        self.label = QLabel(self.formLayoutWidget_3)
        self.label.setObjectName(u"label")

        self.formLayout_3.setWidget(2, QFormLayout.LabelRole, self.label)

        self.label_2 = QLabel(self.formLayoutWidget_3)
        self.label_2.setObjectName(u"label_2")

        self.formLayout_3.setWidget(3, QFormLayout.LabelRole, self.label_2)

        self.ltxtWorkstation = QLineEdit(self.formLayoutWidget_3)
        self.ltxtWorkstation.setObjectName(u"ltxtWorkstation")
        self.ltxtWorkstation.setFocusPolicy(Qt.ClickFocus)

        self.formLayout_3.setWidget(0, QFormLayout.FieldRole, self.ltxtWorkstation)

        self.ltxtInspector = QLineEdit(self.formLayoutWidget_3)
        self.ltxtInspector.setObjectName(u"ltxtInspector")

        self.formLayout_3.setWidget(1, QFormLayout.FieldRole, self.ltxtInspector)

        self.ltxtDUTModel = QLineEdit(self.formLayoutWidget_3)
        self.ltxtDUTModel.setObjectName(u"ltxtDUTModel")

        self.formLayout_3.setWidget(2, QFormLayout.FieldRole, self.ltxtDUTModel)

        self.ltxtDUTSn = QLineEdit(self.formLayoutWidget_3)
        self.ltxtDUTSn.setObjectName(u"ltxtDUTSn")

        self.formLayout_3.setWidget(3, QFormLayout.FieldRole, self.ltxtDUTSn)

        self.scrollArea_2 = QScrollArea(frmMainTest)
        self.scrollArea_2.setObjectName(u"scrollArea_2")
        self.scrollArea_2.setGeometry(QRect(360, 228, 601, 223))
        self.scrollArea_2.setFocusPolicy(Qt.ClickFocus)
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollAreaWidgetContents_2 = QWidget()
        self.scrollAreaWidgetContents_2.setObjectName(u"scrollAreaWidgetContents_2")
        self.scrollAreaWidgetContents_2.setGeometry(QRect(0, 0, 599, 221))
        self.tbView = QTableView(self.scrollAreaWidgetContents_2)
        self.tbView.setObjectName(u"tbView")
        self.tbView.setGeometry(QRect(0, 6, 595, 211))
        self.tbView.setFont(font)
        self.tbView.setFocusPolicy(Qt.ClickFocus)
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_2)
        self.btnNewReport = QPushButton(frmMainTest)
        self.btnNewReport.setObjectName(u"btnNewReport")
        self.btnNewReport.setGeometry(QRect(972, 120, 115, 40))
        self.btnConDev = QPushButton(frmMainTest)
        self.btnConDev.setObjectName(u"btnConDev")
        self.btnConDev.setGeometry(QRect(972, 252, 115, 40))
        self.btnProTest = QPushButton(frmMainTest)
        self.btnProTest.setObjectName(u"btnProTest")
        self.btnProTest.setGeometry(QRect(972, 672, 115, 40))
        self.btnProTest.setFocusPolicy(Qt.ClickFocus)
        self.lblSkipPort = QLabel(frmMainTest)
        self.lblSkipPort.setObjectName(u"lblSkipPort")
        self.lblSkipPort.setGeometry(QRect(972, 300, 91, 16))
        self.txtSkipPort = QTextEdit(frmMainTest)
        self.txtSkipPort.setObjectName(u"txtSkipPort")
        self.txtSkipPort.setGeometry(QRect(972, 324, 115, 103))
        self.txtSkipPort.setFocusPolicy(Qt.ClickFocus)
        self.txtSkipPort.setFrameShape(QFrame.Box)
        self.chkFixOptimize = QCheckBox(frmMainTest)
        self.chkFixOptimize.setObjectName(u"chkFixOptimize")
        self.chkFixOptimize.setGeometry(QRect(972, 516, 115, 16))
        self.chkFixOptimize.setFocusPolicy(Qt.ClickFocus)
        self.chkFixManual = QCheckBox(frmMainTest)
        self.chkFixManual.setObjectName(u"chkFixManual")
        self.chkFixManual.setGeometry(QRect(972, 540, 115, 16))
        self.chkFixManual.setFocusPolicy(Qt.ClickFocus)
        self.label_8 = QLabel(frmMainTest)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(12, 204, 61, 16))
        self.ledDBPath = QLineEdit(frmMainTest)
        self.ledDBPath.setObjectName(u"ledDBPath")
        self.ledDBPath.setGeometry(QRect(78, 204, 493, 19))
        self.ledDBPath.setFocusPolicy(Qt.ClickFocus)
        self.scrollArea_3 = QScrollArea(frmMainTest)
        self.scrollArea_3.setObjectName(u"scrollArea_3")
        self.scrollArea_3.setGeometry(QRect(360, 456, 601, 259))
        self.scrollArea_3.setFocusPolicy(Qt.ClickFocus)
        self.scrollArea_3.setWidgetResizable(True)
        self.scrollAreaWidgetContents_3 = QWidget()
        self.scrollAreaWidgetContents_3.setObjectName(u"scrollAreaWidgetContents_3")
        self.scrollAreaWidgetContents_3.setGeometry(QRect(0, 0, 599, 257))
        self.scrollArea_3.setWidget(self.scrollAreaWidgetContents_3)
        self.btnFixtureTest = QPushButton(frmMainTest)
        self.btnFixtureTest.setObjectName(u"btnFixtureTest")
        self.btnFixtureTest.setGeometry(QRect(972, 630, 115, 40))
        self.btnFixtureTest.setFocusPolicy(Qt.ClickFocus)
        self.chkHVMManual = QCheckBox(frmMainTest)
        self.chkHVMManual.setObjectName(u"chkHVMManual")
        self.chkHVMManual.setGeometry(QRect(972, 564, 115, 16))
        self.chkHVMManual.setFocusPolicy(Qt.ClickFocus)
        self.lblSpecTRow = QLabel(frmMainTest)
        self.lblSpecTRow.setObjectName(u"lblSpecTRow")
        self.lblSpecTRow.setGeometry(QRect(972, 438, 91, 16))
        self.txtSpecTRow = QTextEdit(frmMainTest)
        self.txtSpecTRow.setObjectName(u"txtSpecTRow")
        self.txtSpecTRow.setGeometry(QRect(972, 462, 115, 49))
        self.txtSpecTRow.setFocusPolicy(Qt.ClickFocus)
        self.txtSpecTRow.setFrameShape(QFrame.Box)
        self.label_9 = QLabel(frmMainTest)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(12, 180, 91, 16))
        self.ledDUT_IDN = QLineEdit(frmMainTest)
        self.ledDUT_IDN.setObjectName(u"ledDUT_IDN")
        self.ledDUT_IDN.setGeometry(QRect(78, 180, 493, 19))
        self.ledDUT_IDN.setFocusPolicy(Qt.ClickFocus)
        self.txtMsg = QTextEdit(frmMainTest)
        self.txtMsg.setObjectName(u"txtMsg")
        self.txtMsg.setGeometry(QRect(577, 36, 385, 163))
        self.txtMsg.setFocusPolicy(Qt.ClickFocus)
        self.btnMModify = QPushButton(frmMainTest)
        self.btnMModify.setObjectName(u"btnMModify")
        self.btnMModify.setGeometry(QRect(972, 588, 115, 40))
        self.btnMModify.setFocusPolicy(Qt.ClickFocus)
        self.btnExportRec = QPushButton(frmMainTest)
        self.btnExportRec.setObjectName(u"btnExportRec")
        self.btnExportRec.setGeometry(QRect(972, 210, 115, 40))
        self.ledDataUpload = QLineEdit(frmMainTest)
        self.ledDataUpload.setObjectName(u"ledDataUpload")
        self.ledDataUpload.setGeometry(QRect(576, 204, 385, 19))
        self.ledDataUpload.setFocusPolicy(Qt.ClickFocus)
        QWidget.setTabOrder(self.ltxtWorkstation, self.ltxtInspector)
        QWidget.setTabOrder(self.ltxtInspector, self.ltxtDUTModel)
        QWidget.setTabOrder(self.ltxtDUTModel, self.ltxtDUTSn)
        QWidget.setTabOrder(self.ltxtDUTSn, self.cboScript)
        QWidget.setTabOrder(self.cboScript, self.cboReportNo)
        QWidget.setTabOrder(self.cboReportNo, self.ltxtStartTime)
        QWidget.setTabOrder(self.ltxtStartTime, self.ltxtSpendTime)
        QWidget.setTabOrder(self.ltxtSpendTime, self.btnStart)
        QWidget.setTabOrder(self.btnStart, self.btnStop)
        QWidget.setTabOrder(self.btnStop, self.scrollArea_2)
        QWidget.setTabOrder(self.scrollArea_2, self.scrollArea)
        QWidget.setTabOrder(self.scrollArea, self.btnNewReport)
        QWidget.setTabOrder(self.btnNewReport, self.btnConDev)
        QWidget.setTabOrder(self.btnConDev, self.btnExit)
        QWidget.setTabOrder(self.btnExit, self.tbView)

        self.retranslateUi(frmMainTest)

        QMetaObject.connectSlotsByName(frmMainTest)
    # setupUi

    def retranslateUi(self, frmMainTest):
        frmMainTest.setWindowTitle(QCoreApplication.translate("frmMainTest", u"\u6e2c\u8a66\u4e3b\u8996\u7a97", None))
#if QT_CONFIG(tooltip)
        self.btnStart.setToolTip(QCoreApplication.translate("frmMainTest", u"\u6309\u6b64\u9215\u9032\u884c\u8a2d\u5099\u9023\u7dda\u53ca\u9032\u884c\u6e2c\u8a66 ", None))
#endif // QT_CONFIG(tooltip)
        self.btnStart.setText(QCoreApplication.translate("frmMainTest", u"\u958b\u59cb", None))
#if QT_CONFIG(tooltip)
        self.btnStop.setToolTip(QCoreApplication.translate("frmMainTest", u"\u505c\u6b62\u6e2c\u8a66", None))
#endif // QT_CONFIG(tooltip)
        self.btnStop.setText(QCoreApplication.translate("frmMainTest", u"\u505c\u6b62", None))
#if QT_CONFIG(tooltip)
        self.btnExit.setToolTip(QCoreApplication.translate("frmMainTest", u"\u95dc\u9589\u7a0b\u5f0f", None))
#endif // QT_CONFIG(tooltip)
        self.btnExit.setText(QCoreApplication.translate("frmMainTest", u"\u7d50\u675f", None))
        self.label_5.setText(QCoreApplication.translate("frmMainTest", u"\u6e2c\u8a66\u811a\u672c:", None))
        self.Label.setText(QCoreApplication.translate("frmMainTest", u"\u6e2c\u8a66\u7de8\u865f:", None))
        self.label_6.setText(QCoreApplication.translate("frmMainTest", u"\u958b\u59cb\u6642\u9593:", None))
        self.label_7.setText(QCoreApplication.translate("frmMainTest", u"\u82b1\u8cbb\u6642\u9593:", None))
        self.label_10.setText(QCoreApplication.translate("frmMainTest", u"\u811a\u672c\u7248\u672c:", None))
        self.label_3.setText(QCoreApplication.translate("frmMainTest", u"\u5de5\u4f5c\u7ad9:", None))
        self.label_4.setText(QCoreApplication.translate("frmMainTest", u"\u6aa2\u6e2c\u8005:", None))
        self.label.setText(QCoreApplication.translate("frmMainTest", u"\u6a5f\u5668\u578b\u865f:", None))
        self.label_2.setText(QCoreApplication.translate("frmMainTest", u"\u6a5f\u5668\u5e8f\u865f:", None))
#if QT_CONFIG(tooltip)
        self.ltxtInspector.setToolTip(QCoreApplication.translate("frmMainTest", u"\u8f38\u5165\u6aa2\u6e2c\u8005\u5de5\u865f", None))
#endif // QT_CONFIG(tooltip)
        self.ltxtDUTModel.setText(QCoreApplication.translate("frmMainTest", u"GPT-9804", None))
        self.ltxtDUTSn.setText(QCoreApplication.translate("frmMainTest", u"GEW110100", None))
#if QT_CONFIG(tooltip)
        self.btnNewReport.setToolTip(QCoreApplication.translate("frmMainTest", u"\u7522\u751f\u65b0\u7684\u6e2c\u8a66\u8868", None))
#endif // QT_CONFIG(tooltip)
        self.btnNewReport.setText(QCoreApplication.translate("frmMainTest", u"\u65b0\u6e2c\u8a66", None))
#if QT_CONFIG(tooltip)
        self.btnConDev.setToolTip(QCoreApplication.translate("frmMainTest", u"\u9032\u884c\u8a2d\u5099\u9023\u7dda\u78ba\u8a8d, \u4e0d\u57f7\u884c\u6e2c\u8a66", None))
#endif // QT_CONFIG(tooltip)
        self.btnConDev.setText(QCoreApplication.translate("frmMainTest", u"\u8a2d\u5099\u78ba\u8a8d", None))
#if QT_CONFIG(tooltip)
        self.btnProTest.setToolTip(QCoreApplication.translate("frmMainTest", u"\u7a0b\u5f0f\u958b\u767c\u6642, \u7247\u6bb5\u7a0b\u5f0f\u6e2c\u8a66\u7528.", None))
#endif // QT_CONFIG(tooltip)
        self.btnProTest.setText(QCoreApplication.translate("frmMainTest", u"\u4e0a\u50b3\u8cc7\u6599", None))
        self.lblSkipPort.setText(QCoreApplication.translate("frmMainTest", u"\u4e0d\u6aa2\u67e5\u57e0:", None))
#if QT_CONFIG(tooltip)
        self.txtSkipPort.setToolTip(QCoreApplication.translate("frmMainTest", u"\u8a2d\u5099\u9023\u7dda\u78ba\u8a8d\u6642, \u6709\u8a2d\u5099\u672a\u9023\u63a5\u6642, \u518d\u6b21\u6383\u63cf\u96fb\u8166\u9023\u63a5\u57e0\u6642, \n"
"\u90a3\u4e9b\u57e0\u78ba\u5b9a\u6ca1\u6709\u7528, \u8981\u7565\u904e\u6aa2\u67e5, \u7bc0\u7701\u9023\u7dda\u6642\u9593.", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(tooltip)
        self.chkFixOptimize.setToolTip(QCoreApplication.translate("frmMainTest", u"\u52fe\u9078:\u4f9d\u6cbb\u5177\u689d\u4ef6\u5217\u8868\u9806\u5e8f\u9032\u884c\u6e2c\u8a66, \u53ef\u6e1b\u5c11\u63db\u7dda\u983b\u7387.\n"
"\u672a\u52fe\u9078:\u4f9d\u6e2c\u8a66\u9805\u76ee\u9806\u5e8f\u9032\u884c\u6e2c\u8a66.", None))
#endif // QT_CONFIG(tooltip)
        self.chkFixOptimize.setText(QCoreApplication.translate("frmMainTest", u"\u6cbb\u5177\u63a7\u5236\u512a\u5316", None))
#if QT_CONFIG(tooltip)
        self.chkFixManual.setToolTip(QCoreApplication.translate("frmMainTest", u"\u52fe\u9078:\u624b\u52d5\u63db\u7dda\u63a5\u6cbb\u5177\n"
"\u672a\u52fe\u9078:\u81ea\u52d5\u5207\u63dbATE\u6cbb\u5177\u9032\u884c\u63db\u7dda.", None))
#endif // QT_CONFIG(tooltip)
        self.chkFixManual.setText(QCoreApplication.translate("frmMainTest", u"\u624b\u52d5\u63a5\u7dda\u6cbb\u5177", None))
        self.label_8.setText(QCoreApplication.translate("frmMainTest", u"\u8cc7\u6599\u5eab:", None))
#if QT_CONFIG(tooltip)
        self.btnFixtureTest.setToolTip(QCoreApplication.translate("frmMainTest", u"\u52fe\u9078\u6cbb\u5177\u689d\u4ef6\u5217\u8868, \u9032\u884c\u6cbb\u5177\u958b\u95dc\u5207\u63db\u78ba\u8a8d.\n"
"\u52fe\u9078\u9805\u76ee>1\u500b\u6642, 5\u79d2\u81ea\u52d5\u5207\u63db\u5230\u4e0b\u500b\u9805\u76ee", None))
#endif // QT_CONFIG(tooltip)
        self.btnFixtureTest.setText(QCoreApplication.translate("frmMainTest", u"\u6cbb\u5177\u6e2c\u8a66", None))
#if QT_CONFIG(tooltip)
        self.chkHVMManual.setToolTip(QCoreApplication.translate("frmMainTest", u"\u52fe\u9078:\u624b\u586b\u9ad8\u58d3\u8868\u8b80\u503c.\n"
"\u672a\u52fe\u9078:\u4f7f\u7528\u53ef\u9023\u7dda\u7684vitrek 4700\u81ea\u52d5\u8b80\u503c", None))
#endif // QT_CONFIG(tooltip)
        self.chkHVMManual.setText(QCoreApplication.translate("frmMainTest", u"\u624b\u586b\u9ad8\u58d3\u8868\u503c", None))
        self.lblSpecTRow.setText(QCoreApplication.translate("frmMainTest", u"\u6307\u5b9a\u6e2c\u8a66\u5217:", None))
#if QT_CONFIG(tooltip)
        self.txtSpecTRow.setToolTip(QCoreApplication.translate("frmMainTest", u"\u7a7a\u767d, \u4f9d\u5de6\u5074\u6e2c\u8a66\u9805\u76ee\u53ca\u6cbb\u5177\u689d\u4ef6\u5217\u8868\u52fe\u9078\u9805\u76ee\u9032\u884c\u6e2c\u8a66.\n"
"\u586b\u5165\u6578\u503c(\u53ef','\u5206\u958b, '-'\u6307\u5b9a\u7bc4\u570d), \u6e2c\u8a66\u6307\u5b9a\u7684\u5217.\n"
"\u8a3b:\u6e2c\u8a66\u9805\u76ee, \u6cbb\u5177\u689d\u4ef6\u5217\u8868\u53ca\u6307\u5b9a\u6e2c\u8a66\u5217\u70ba\u4ea4\u96c6\u95dc\u4fc2.", None))
#endif // QT_CONFIG(tooltip)
        self.label_9.setText(QCoreApplication.translate("frmMainTest", u"\u6a5f\u5668IDN:", None))
#if QT_CONFIG(tooltip)
        self.btnMModify.setToolTip(QCoreApplication.translate("frmMainTest", u"\u5728\"\u6307\u5b9a\u6e2c\u8a66\u5217\"\u586b\u5165\u8981\u4fee\u6539\u7684\u5217\u865f, \u6309\u6b64\u9215\u9032\u884c\u4e3b\u91cf\u6e2c\u503c\u4fee\u6539", None))
#endif // QT_CONFIG(tooltip)
        self.btnMModify.setText(QCoreApplication.translate("frmMainTest", u"\u624b\u52d5\u4fee\u8a02\u6e2c\u503c", None))
#if QT_CONFIG(tooltip)
        self.btnExportRec.setToolTip(QCoreApplication.translate("frmMainTest", u"\u9032\u884c\u8a2d\u5099\u9023\u7dda\u78ba\u8a8d, \u4e0d\u57f7\u884c\u6e2c\u8a66", None))
#endif // QT_CONFIG(tooltip)
        self.btnExportRec.setText(QCoreApplication.translate("frmMainTest", u"\u8f38\u51fa\u6e2c\u8a66\u8a18\u9304", None))
    # retranslateUi

