# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\Users\lorenzo_wang\OneDrive\文件\Project_Python\GPT99ATE\frmTRecord.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_frmTRecord(object):
    def setupUi(self, frmTRecord):
        frmTRecord.setObjectName("frmTRecord")
        frmTRecord.resize(1280, 720)
        self.tbview = QtWidgets.QTableView(frmTRecord)
        self.tbview.setGeometry(QtCore.QRect(12, 30, 1261, 679))
        self.tbview.setObjectName("tbview")

        self.retranslateUi(frmTRecord)
        QtCore.QMetaObject.connectSlotsByName(frmTRecord)

    def retranslateUi(self, frmTRecord):
        _translate = QtCore.QCoreApplication.translate
        frmTRecord.setWindowTitle(_translate("frmTRecord", "Form"))
